### ISSUE TITLE
Allow override of package.json author

### ISSUE THREAD

**Issue by RichardLitt** [Laoujin/licenser#13]
Sometimes, the license does not belong to the `package.json` author - for instance, if they are working for a business. There should be a way to override grabbing the author.

**Comment by Laoujin** [comment]
At the moment it is the other way around: `licenser config --author="some name"` will be used whenever there is no package.json or no author in it.

You can use this global config with `licenser set -g`. Perhaps that is what you need?

If this is a one time thing, you can also `licenser set --author="Your Name"`

**Comment by RichardLitt** [comment]
Apologies! I should have written this out more.

In [this repo](https://github.com/shutterstock/bigstock-node-client/blob/master/LICENSE.md), the License holder is `Shutterstock Images, LLC`. However, running `licenser` replaces it with the author from the `package.json`. You're right, I could have used `licenser set MIT --author="Shutterstock Images, LLC"`.

Marking this as resolved.
